name: Thanks for contribution

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  send_msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const number = context.payload.pull_request
              ? context.payload.pull_request.number
              : context.payload.issue.number;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: "Thanks for contribution"
            });
